config/routes.rb
Rails.application.routes.draw do
  # resources :trackers
  root "pages#hero_section"
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :dry_foods, only: [ :new, :create, :index, :destroy, :show ]
    resources :pets do
      resources :trackers do
        collection do
          post :import
          get "favorite_food"
          delete :bulk_delete
        end
      end
    end
    resource :session, except: [ :new ]
    resource :registrations, only: [ :new, :create ]
    resource :timezone, only: [ :create ]
    resource :users, except: [ :new ]
    # get '/signup', to: "registrations#new", as: :new_registrations
    # post 'registration/create', to: "registrations#create", as: :registrations
    get "/login", to: "sessions#new", as: :new_session
    resources :passwords, only: [ :new, :create, :edit, :update ], param: :token
    get "/home", to: "pages#hero_section"
    get "/about", to: "pages#about"
    get "/doc", to: "pages#doc"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "auth/:provider/callback", to: "omni_auth/sessions#create"
  post "auth/:provider/callback", to: "omni_auth/sessions#create"
  get "auth/failure", to: "omni_auth/sessions#failure"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :connected_services, dependent: :destroy
  has_many :sessions, dependent: :destroy
  has_many :pets, dependent: :destroy
  has_many :dry_foods, dependent: :destroy
  validates_associated :pets

  attr_accessor :email_address_confirmation

  validates :username, presence: true
  validates :email_address, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }, allow_nil: true
  validates :email_address, confirmation: true, on: :create
  validates :password, presence: true,
                    length: { maximum: 105 }
  validates :password_confirmation, presence: true
  validates :timezone, presence: true, on: :create

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  def new_user?
    sign_in_count == 1
  end

  def self.from_omniauth(auth)
    # Find the connected account first
    connected_service = ConnectedService.find_by(provider: auth.provider, uid: auth.uid)

    # If the connected account exists, return its user
    return connected_service.user if connected_service

    # If no connected account, find or create the user by email
    user = User.find_or_initialize_by(email_address: auth.info.email)

    # If the user is new, set their details
    if user.new_record?
      user.name = auth.info.name       # Assuming you have a 'name' attribute
      user.password = SecureRandom.hex # Set a random password for OAuth users
      # You might want to skip email confirmation for OAuth users if you have that feature
    end

    # Associate the new provider with the user
    user.connected_services.build(provider: auth.provider, uid: auth.uid)

    user.save
    user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]
  before_action :authenticated?, only: %i[edit update destroy]

  def edit
    @user = Current.user
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: t(".update.notice") }
        format.json { render :show, status: :ok, location: users_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy!
    name = @user.username.split(" ").map(&:capitalize).join(" ")
    session[:user_id] = nil if @user == Current.user

    respond_to do |format|
      format.html { redirect_to "/home", status: :see_other, alert: t(".destroy.alert", name: name) }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = Current.user
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :timezone)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container mx-auto mb-4 mt-2">
  <div class="flex flex-col justify-center bg-gray-50 dark:bg-gray-800 border-2 border-gray-300 shadow-md rounded-lg p-4 sm:p-6">
    <div class="mx-auto mb-6">
      <h1 class="text-center font-semibold text-xl capitalize md:text-2xl lg:text-4xl"><%= t(".title", username: Current.user.username.split(' ').map(&:capitalize).join(" ")) %></h1>
    </div>

    <%= form_with(model: @user, url: users_path, method: :patch) do |form| %>
      <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row">
        <div class="flex justify-center md:justify-end md:w-1/3">
          <label for="" class="text-base font-medium text-gray-700 dark:text-gray-100 capitalize required"><%= t(".username") %></label>
        </div>
        <div class="flex flex-col items-center md:items-start md:w-5/6">
          <%= form.text_field :username, value: @user.username, class: "shadow-md rounded-md border border-gray-400 focus:outline-softBlue px-3 py-2 w-1/2 dark:text-black", :required => true %>
        </div>
      </div>

      <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row">
        <div class="flex justify-center md:justify-end md:w-1/3">
          <label for="" class="text-base font-medium text-gray-700 dark:text-gray-100 capitalize required"><%= t(".email") %></label>
        </div>
        <div class="flex flex-col items-center md:items-start md:w-5/6">
          <%= form.email_field :email_address, required: true, value: @user.email_address, class: "dark:text-black shadow-md rounded-md border border-gray-400 focus:outline-blue-400 px-3 py-2 w-1/2 #{'border-red-500' if form.object.errors[:email_address].any?}" %>
          <% form.object.errors.full_messages_for(:email_address).each do |message| %>
            <p class="text-red-500 text-sm italic mt-1">
              <%= message %>
            </p> 
          <% end %>
        </div>
      </div>

      <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row">
        <div class="flex justify-center md:justify-end md:w-1/3">
          <label for="" class="text-base font-medium text-gray-700 dark:text-gray-100 capitalize required"><%= t(".password") %></label>
        </div>
        <div class="flex flex-col items-center md:items-start md:w-5/6">
          <%= form.password_field :password, required: true, placeholder: t(".password_placeholder"), class: "dark:text-black shadow-md rounded-md border border-gray-400 focus:outline-blue-400 px-3 py-2 w-1/2 #{'border-red-500' if form.object.errors[:password].any?}" %>
          <% form.object.errors.full_messages_for(:password).each do |message| %>
            <p class="text-red-500 text-sm italic mt-1">
              <%= message %>
            </p>
          <% end %>
        </div>
      </div>

      <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row">
        <div class="flex justify-center md:justify-end md:w-1/3">
          <label for="" class="text-base font-medium text-gray-700 dark:text-gray-100 capitalize required"><%= t(".password_confirmation") %></label>
        </div>
        <div class="flex flex-col items-center md:items-start md:w-5/6">
          <%= form.password_field :password_confirmation, required: true, autocomplete: "current-password", placeholder: t(".password_confirmation_placeholder"), class: "dark:text-black shadow-md rounded-md border border-gray-400 focus:outline-blue-400 px-3 py-2 w-1/2 #{'border-red-500' if form.object.errors[:password_confirmation].any?}" %>
          <% form.object.errors.full_messages_for(:password_confirmation).each do |message| %>
            <p class="text-red-500 text-sm italic mt-1">
              <%= message %>
            </p>
          <% end %>
        </div>
      </div>

      <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row" data-controller="time-zone">
        <div class="flex justify-center md:justify-end md:w-1/3">
          <%= form.label :timezone, t(".timezone"), class: "text-base font-medium text-gray-700 dark:text-gray-100 capitalize" %>
        </div>
        <% if @user.timezone.nil? %>
          <div class="flex flex-col items-center md:items-start md:w-5/6">
            <%= form.text_field :timezone, data: {"time_zone_target" => "tz"}, class: "dark:text-black shadow-md rounded-md border border-gray-400 bg-gray-100 px-3 py-2 w-1/2 focus:outline-none", readonly: true %>
          </div>
        <% else %>
          <div class="flex flex-col items-center md:items-start md:w-5/6">
            <%= form.text_field :timezone, value: @user.timezone, class: "dark:text-black dark:bg-gray-300 shadow-md rounded-md border border-gray-400 bg-gray-100 px-3 py-2 w-1/2 focus:outline-none", readonly: true %>
            <span class="mt-2 text-sm italic"><%= t(".timezone_readonly_note") %></span>
          </div>
        <% end %>
      </div>

      <div class="flex flex-col justify-center items-center space-x-4 mb-4 md:flex-row">
        <div class="mb-4">
          <%= form.submit t(".update_profile_button"), class: "text-center rounded-md px-3.5 py-2.5 text-white bg-softBlue hover:bg-white hover:text-softBlue hover:border-2 hover:border-softBlue inline-block font-medium cursor-pointer" %>
        </div>
        <div class="mb-4">
          <%= link_to t(".cancel_button", username: @user.username.split(" ").map(&:capitalize).join(" ")), users_path, class: "text-center rounded-md px-3.5 py-2.5 text-white bg-grayishBlue hover:bg-white hover:text-grayishBlue hover:border-2 hover:border-grayishBlue inline-block font-medium cursor-pointer" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mx-auto mb-2 mt-8 w-full md:w-1/2" data-controller="timezone">
  <div class="flex flex-col px-6 py-4 border border-2 border-slate-300 rounded-lg shadow-sm divide-y-2 divide-slate-200">
    <div class="flex flex-col justify-center">
      <div class='flex flex-col justify-center text-center mb-3'>
        <h1 class="text-2xl text-center font-bold underline underline-offset-4 mt-4 mb-4 md:text-4xl"><%= t(".title", username: Current.user.username.split(' ').map(&:capitalize).join(' ')) %></h1>
      </div>

      <div class='flex flex-col justify-center text-center mb-3'>
        <div class="flex justify-center text-lg space-x-3 mb-2 md:text-2xl">
          <strong class="capitalize"><%= t(".username") %></strong>
          <div class="flex">
            <%= Current.user.username.split(' ').map(&:capitalize).join(' ') %>
          </div>
        </div>

        <div class="flex justify-center text-lg space-x-3 mb-2 md:text-2xl">
          <strong class="capitalize"><%= t(".email") %></strong>
          <div class="flex">
            <%= Current.user.email_address %>
          </div>
        </div>

        <div class="flex justify-center text-lg space-x-3 mb-2 md:text-2xl">
          <strong class="capitalize"><%= t(".timezone") %></strong>
          <div class="flex">
            <%= Current.user.timezone %>
          </div>
        </div>

        <div class="flex justify-center text-lg space-x-3 mb-2 md:text-2xl">
          <strong class="capitalize"><%= t(".pets_count") %></strong>
          <div class="flex flex-col">
            <%= Current.user.pets.count %> <%= t(".pets") %>
          </div>
        </div>
        <div class="flex justify-center text-lg space-x-3 mb-2 md:text-2xl">
          <% Current.user.pets.each do |pet| %>
            <%= link_to "#{pet.petname.capitalize}", pet_path(pet), class: "text-grayishBlue underline decoration-2 decoration-grayishBlue transition duration-300 ease-in-out hover:text-softRed hover:decoration-softRed hover:scale-110" %>
          <% end %>
        </div>

      </div>
    </div>

    <div class="flex justify-center text-center space-x-4 mt-3">
      <%= link_to t(".go_to_cats_list", username: Current.user.username.split(" ").map(&:capitalize).join(" ")), pets_path, class: "p-4 mt-4 text-sm font-semibold text-orange-600 bg-orange-200 rounded shadow-md border-2 border-orange-200 transition duration-300 ease-in-out hover:scale-110 md:text-base hover:bg-white hover:text-orange-500 capitalize" %>
      <%= link_to t(".edit_profile_button"), edit_users_path(Current.user), class: "p-4 mt-4 text-sm font-semibold text-green-600 bg-green-200 rounded shadow-md border-2 border-green-200 transition duration-300 ease-in-out hover:scale-110 md:text-base hover:bg-white hover:text-green-500 capitalize" %>
      <%= link_to t(".delete_profile_button"), users_path, class: "p-4 mt-4 text-sm font-semibold text-red-600 bg-red-200 rounded shadow-md border-2 border-red-200 transition duration-300 ease-in-out hover:scale-110 md:text-base hover:bg-white hover:text-red-500 capitalize", data: {"turbo-confirm":  t(".delete_confirm"), "turbo-method": "delete"} %>
    </div>
  </div>
</div>