config/routes.rb
Rails.application.routes.draw do
  # resources :trackers
  root "pages#hero_section"
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :dry_foods, only: [ :new, :create, :index, :destroy, :show ]
    resources :pets do
      resources :trackers do
        collection do
          post :import
          get "favorite_food"
          delete :bulk_delete
        end
      end
    end
    resource :session, except: [ :new ]
    resource :registrations, only: [ :new, :create ]
    resource :timezone, only: [ :create ]
    resource :users, except: [ :new ]
    # get '/signup', to: "registrations#new", as: :new_registrations
    # post 'registration/create', to: "registrations#create", as: :registrations
    get "/login", to: "sessions#new", as: :new_session
    resources :passwords, only: [ :new, :create, :edit, :update ], param: :token
    get "/home", to: "pages#hero_section"
    get "/about", to: "pages#about"
    get "/doc", to: "pages#doc"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "auth/:provider/callback", to: "omni_auth/sessions#create"
  post "auth/:provider/callback", to: "omni_auth/sessions#create"
  get "auth/failure", to: "omni_auth/sessions#failure"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/dry_food.rb
class DryFood < ApplicationRecord
  belongs_to :user
  has_many :trackers, dependent: :nullify

  enum :food_type, { kibble: "Kibble", freeze_dried: "Freeze-Dried" }

  before_create :set_left_amount

  def brand_with_description
    "#{brand} - #{description}"
  end

  def update_used_amount!
    with_lock do
      total_consumed = trackers.sum(:amount)
      daily_sums = trackers.group(:date).sum(:amount).values
      avg_daily = daily_sums.any? ? (daily_sums.sum.to_f / daily_sums.size).round(2) : 0
      remaining = [ amount - total_consumed, 0 ].max
      days_left = avg_daily > 0 ? (remaining / avg_daily).to_i : 0
      end_date = avg_daily > 0 ? Time.current + days_left.days : nil
      update_columns(
        total_ate_amount: total_consumed,
        used_amount: amount,
        left_amount: remaining,
        average_used_amount: avg_daily,
        days_remaining: end_date
      )
    end
  end

  private

  def set_left_amount
    self.left_amount = amount
  end
end

app/controllers/dry_foods_controller.rb
class DryFoodsController < ApplicationController
  before_action :set_dry_food, only: %i[ show destroy ]

  # GET /dry_foods or /dry_foods.json
  def index
    @dry_foods = Current.user.dry_foods
    respond_to do |format|
      format.html
      format.json { render json: @dry_foods }
    end
  end

  # GET /dry_foods/1 or /dry_foods/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @dry_food }
    end
  end

  # GET /dry_foods/new
  def new
    @dry_food = Current.user.dry_foods.build
  end

  # POST /dry_foods or /dry_foods.json
  def create
    @dry_food = Current.user.dry_foods.build(dry_food_params)

    respond_to do |format|
      if @dry_food.save
        format.html { redirect_to dry_foods_path, notice: t(".notice") }
        format.json { render :show, status: :created, location: dry_foods_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dry_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dry_foods/1 or /dry_foods/1.json
  def destroy
    @dry_food.destroy!

    respond_to do |format|
      format.html { redirect_to dry_foods_path, notice: t(".notice"), status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dry_food
      @dry_food = Current.user.dry_foods.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.html do
          flash[:alert] = t("dry_foods.not_found")
          redirect_to dry_foods_path
        end
        format.json { render json: { error: t("dry_foods.not_found") }, status: :not_found }
      end
    end

    # Only allow a list of trusted parameters through.
    def dry_food_params
      params.require(:dry_food).permit(:brand, :food_type, :description, :amount, :used_amount, :user_id)
    end
end

app/helpers/dry_foods_helper.rb
module DryFoodsHelper
end

app/views/dry_foods/_dry_food.html.erb
<div id="<%= dom_id dry_food %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1"><%= t('.brand') %>:</strong>
    <%= dry_food.brand %>
  </div>
  <div>
    <strong class="block font-medium mb-1"><%= t('.food_type') %>:</strong>
    <%= dry_food.food_type %>
  </div>
  <div>
    <strong class="block font-medium mb-1"><%= t('.description') %>:</strong>
    <%= dry_food.description %>
  </div>
  <div>
    <strong class="block font-medium mb-1"><%= t('.amount') %>:</strong>
    <%= dry_food.amount %>
  </div>
  <div>
    <strong class="block font-medium mb-1"><%= t('.used_amount') %>:</strong>
    <%= dry_food.used_amount %>
  </div>
  <div>
    <strong class="block font-medium mb-1"><%= t('.average_used_amount') %>:</strong>
    <%= dry_food.average_used_amount %>
  </div>
  <div>
    <strong class="block font-medium mb-1"><%= t('.total_ate_amount') %>:</strong>
    <%= dry_food.total_ate_amount %>
  </div>
  <div>
    <strong class="block font-medium mb-1"><%= t('.left_amount') %>:</strong>
    <%= dry_food.left_amount %>
  </div>
  <div>
    <strong class="block font-medium mb-1"><%= t('.days_remaining') %>:</strong>
    <%= dry_food.days_remaining %>
  </div>
  <div>
    <strong class="block font-medium mb-1"><%= t('.user') %>:</strong>
    <%= dry_food.user_id %>
  </div>
</div>

app/views/dry_foods/_form.html.erb
<%= form_with(model: dry_food, id: "dry-food-form", class: "contents") do |form| %>
  <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row">
    <%= render 'shared/errors', obj: @dry_food %>
  </div>

  <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row">
    <div class="flex justify-center md:justify-end md:w-1/3">
      <%= form.label :brand, t(".brand"), class: "text-base font-medium text-gray-700 dark:text-gray-100 capitalize required"%>
    </div>
    <div class="flex flex-col items-center md:items-start md:w-5/6">
      <%= form.text_field :brand, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full dark:text-black", {"border-gray-400 focus:outline-blue-600": dry_food.errors[:brand].none?, "border-red-400 focus:outline-red-600": dry_food.errors[:brand].any?}] %>
    </div>
  </div>

  <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row">
    <div class="flex justify-center md:justify-end md:w-1/3">
      <%= form.label :food_type, t(".food_type"), class: "text-base font-medium text-gray-700 dark:text-gray-100 capitalize required" %>
    </div>
    <div class="flex flex-col items-center md:items-start md:w-5/6">
      <%= form.select :food_type, DryFood.food_types.keys.map { |ft| [t(".#{ft}"), ft.to_s] }, { prompt: t('.prompt') }, required: true, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full capitalize dark:text-black", {"border-gray-400 focus:outline-blue-600": dry_food.errors[:food_type].none?, "border-red-400 focus:outline-red-600": dry_food.errors[:food_type].any?}] %>
    </div>
  </div>

  <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row">
    <div class="flex justify-center md:justify-end md:w-1/3">
      <%= form.label :description, t(".description"), class: "text-base font-medium text-gray-700 dark:text-gray-100 capitalize required" %>
    </div>
    <div class="flex flex-col items-center md:items-start md:w-5/6">
      <%= form.text_field :description, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full dark:text-black", {"border-gray-400 focus:outline-blue-600": dry_food.errors[:description].none?, "border-red-400 focus:outline-red-600": dry_food.errors[:description].any?}] %>
    </div>
  </div>

  <div class="flex flex-col justify-center space-x-3 items-center mb-4 md:flex-row">
    <div class="flex justify-center md:justify-end md:w-1/3">
      <%= form.label :amount, t(".amount"), class: "text-base font-medium text-gray-700 dark:text-gray-100 capitalize required" %>
    </div>
    <div class="flex flex-col items-center md:items-start md:w-5/6">
      <%= form.number_field :amount, step: :any, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full dark:text-black", {"border-gray-400 focus:outline-blue-600": dry_food.errors[:amount].none?, "border-red-400 focus:outline-red-600": dry_food.errors[:amount].any?}] %>
    </div>
  </div>
<% end %>

app/views/dry_foods/edit.html.erb
<% content_for :title, t('.title') %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl"><%= t('.title') %></h1>

  <%= render "form", dry_food: @dry_food %>

  <%= link_to t('.show'), @dry_food, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to t('.back'), dry_foods_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/dry_foods/index.html.erb
<% content_for :title, t('.title') %>

<div class="container mx-auto w-full overflow-auto shadow-lg rounded-xl mb-4 md:w-5/6">
  <div class="flex flex-col justify-center items-center mb-3">
    <h1 class="text-center font-bold text-2xl mt-5 capitalize md:text-4xl"><%= t('.header') %></h1>
  </div>

  <div class="flex flex-row justify-center items-center space-x-3">
    <%= image_tag('add_dry_food_removebg.png', width:'50px', height: '50px') %>
    <%= link_to t('.add'), new_dry_food_path, class: "text-sky-500 text-lg underline decoration-2 decoration-sky-500 font-bold transition duration-300 ease-in-out hover:scale-110 capitalize md:text-xl" %>
  </div>

  <div id="dry_foods" class="flex flex-col gap-8 justify-center items-center mt-4 lg:flex-row">
    <% if @dry_foods.any? %>
      <!-- Standard Table for Medium and Larger Screens -->
      <div class="hidden lg:block overflow-x-auto">
        <table class="table-auto mb-2 px-2 w-full dark:bg-slate-200">
          <thead>
            <tr class="border-b-4 bg-gray-100 dark:bg-black">
              <th class="capitalize text-sm text-center p-2 dark:text-white">#</th>
              <th class="capitalize text-sm text-center p-2 dark:text-white"><%= t('.brand') %></th>
              <th class="capitalize text-sm text-center p-2 dark:text-white"><%= t('.description') %></th>
              <th class="capitalize text-sm text-center p-2 dark:text-white"><%= t('.type') %></th>
              <th class="capitalize text-sm text-center p-2 dark:text-white"><%= t('.amount') %></th>
              <th class="capitalize text-sm text-center p-2 dark:text-white"><%= t('.total_used_amount') %></th>
              <th class="capitalize text-sm text-center p-2 dark:text-white"><%= t('.average_used_amount') %></th>
              <th class="capitalize text-sm text-center p-2 dark:text-white"><%= t('.left_amount') %></th>
              <th class="capitalize text-sm text-center p-2 dark:text-white"><%= t('.expected_running_out') %></th>
              <th class="capitalize text-sm text-center p-2 dark:text-white"><%= t('.delete') %></th>
            </tr>
          </thead>
          <tbody>
            <% @dry_foods.select(&:persisted?).each_with_index do |food, idx| %>
              <tr class="border-b">
                <td class="capitalize text-sky-700 text-sm text-center font-semibold p-2"><%= idx+1 %></td>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.brand %></td>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.description %></td>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.food_type %></td>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.amount %></td>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.total_ate_amount %></td>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.average_used_amount %></td>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.left_amount %></td>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.days_remaining %></td>
                <td class="capitalize text-sky-700 text-sm text-center p-2">
                  <%= link_to(dry_food_path(food), data: { turbo_method: :delete, turbo_confirm: t('.confirm') }, id: "delete_dry_food_#{food.id}", class: "inline-block transition-transform text-red-400 hover:text-red-600 hover:scale-110") do %>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                    </svg>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <!-- Transposed Table for Small Screens -->
      <div class="block lg:hidden overflow-x-auto">
        <table class="table-auto mb-2 px-2 w-full dark:bg-slate-200">
          <tbody>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black">#</th>
              <% @dry_foods.select(&:persisted?).each_with_index do |food, idx| %>
                <td class="capitalize text-sky-700 text-sm text-center font-semibold p-2"><%= idx+1 %></td>
              <% end %>
            </tr>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black"><%= t('.brand') %></th>
              <% @dry_foods.select(&:persisted?).each do |food| %>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.brand %></td>
              <% end %>
            </tr>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black"><%= t('.description') %></th>
              <% @dry_foods.select(&:persisted?).each do |food| %>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.description %></td>
              <% end %>
            </tr>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black"><%= t('.type') %></th>
              <% @dry_foods.select(&:persisted?).each do |food| %>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.food_type %></td>
              <% end %>
            </tr>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black"><%= t('.amount') %></th>
              <% @dry_foods.select(&:persisted?).each do |food| %>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.amount %></td>
              <% end %>
            </tr>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black"><%= t('.total_used_amount') %></th>
              <% @dry_foods.select(&:persisted?).each do |food| %>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.total_ate_amount %></td>
              <% end %>
            </tr>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black"><%= t('.average_used_amount') %></th>
              <% @dry_foods.select(&:persisted?).each do |food| %>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.average_used_amount %></td>
              <% end %>
            </tr>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black"><%= t('.left_amount') %></th>
              <% @dry_foods.select(&:persisted?).each do |food| %>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.left_amount %></td>
              <% end %>
            </tr>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black"><%= t('.expected_running_out') %></th>
              <% @dry_foods.select(&:persisted?).each do |food| %>
                <td class="capitalize text-sky-700 text-sm text-center p-2"><%= food.days_remaining %></td>
              <% end %>
            </tr>
            <tr class="dark:text-white">
              <th class="capitalize text-sm text-left p-2 bg-gray-100 border-r-4 dark:bg-black"><%= t('.delete') %></th>
              <% @dry_foods.select(&:persisted?).each do |food| %>
                <td class="capitalize text-sky-700 text-sm text-center p-2">
                  <%= link_to(dry_food_path(food), data: { turbo_method: :delete, turbo_confirm: t('.confirm') }, id: "delete_dry_food_#{food.id}", class: "inline-block transition-transform text-red-400 hover:text-red-600 hover:scale-110") do %>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                    </svg>
                  <% end %>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    <% else %>
      <h3 class="text-xl font-light text-center my-10 md:text-lg"><%= t('.no_dry_food') %></h3>
    <% end %>
  </div>
</div>

app/views/dry_foods/new.html.erb
<% content_for :title, t('.title') %>

<div class="mx-auto md:w-2/3 w-full">
  <div class="flex flex-col justify-center mb-4 dark:bg-gray-800 border-2 border-gray-200 shadow-md rounded-lg p-4 sm:p-6">
    <h1 class="text-center font-bold text-4xl mt-4 capitalize md:text-xl"><%= t('.header') %> 🧆</h1>

    <%= render "form", dry_food: @dry_food %>

    
    <div class="flex flex-col justify-center items-center gap-4 mb-4 pt-4 md:flex-row">
      <div class="flex flex-col justify-center">
        <%= button_tag(t('.add'), type: "submit", form: "dry-food-form", class: "btn text-center rounded-md px-3.5 py-2.5 text-white bg-softBlue hover:bg-white hover:text-softBlue hover:border-2 hover:border-softBlue inline-block font-medium cursor-pointer capitalize") %>
      </div>
      <div class="flex flex-col justify-center">
        <%= link_to t('.back'), dry_foods_path, class: "text-center rounded-md px-3.5 py-2.5 text-white bg-gray-500 hover:bg-white hover:text-gray-500 hover:border-2 hover:border-gray-500 inline-block font-medium cursor-pointer capitalize" %>
      </div>
    </div>
  </div>
</div>

app/views/dry_foods/show.html.erb
<% content_for :title, t('.title') %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl"><%= t('.header') %></h1>

  <%= render @dry_food %>

  <%= link_to t('.edit'), edit_dry_food_path(@dry_food), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to t('.back'), dry_foods_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to t('.destroy'), @dry_food, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: t('.confirm') } %>
</div>