config/routes.rb
Rails.application.routes.draw do
  # resources :trackers
  root "pages#hero_section"
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :dry_foods, only: [ :new, :create, :index, :destroy, :show ]
    resources :pets do
      resources :trackers do
        collection do
          post :import
          get "favorite_food"
          delete :bulk_delete
        end
      end
    end
    resource :session, except: [ :new ]
    resource :registrations, only: [ :new, :create ]
    resource :timezone, only: [ :create ]
    resource :users, except: [ :new ]
    # get '/signup', to: "registrations#new", as: :new_registrations
    # post 'registration/create', to: "registrations#create", as: :registrations
    get "/login", to: "sessions#new", as: :new_session
    resources :passwords, only: [ :new, :create, :edit, :update ], param: :token
    get "/home", to: "pages#hero_section"
    get "/about", to: "pages#about"
    get "/doc", to: "pages#doc"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "auth/:provider/callback", to: "omni_auth/sessions#create"
  post "auth/:provider/callback", to: "omni_auth/sessions#create"
  get "auth/failure", to: "omni_auth/sessions#failure"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/tracker.rb
class Tracker < ApplicationRecord
  belongs_to :pet
  belongs_to :dry_food, optional: true
  before_save { self.brand = brand.downcase }
  before_save { self.description = description.downcase }

  enum :food_type, { kibble: "Kibble", freeze_dried: "Freeze-Dried", wet: "Wet", other: "Other" }
  HUNGRY_MAP = {
    eat_right_away: "💖 Yes, eat right away",
    ate_a_little: "🔺 No, not really. Ate A Little",
    not_interested: "❌ No, not interested"
  }
  enum :hungry, HUNGRY_MAP

  validates :food_type, presence: true
  validates :brand, presence: true, length: { minimum: 1, maximum: 50 }
  validates :description, presence: true, length: { minimum: 2, maximum: 100 }
  validates :amount, numericality: true, comparison: { greater_than: 0 }
  validates :left_amount, numericality: true, comparison: { less_than_or_equal_to: :amount }, on: :update, allow_nil: true
  validate :amount_less_than_dry_food_left_amount, if: :dry_food?



  private

  def dry_food?
    (kibble? || freeze_dried?) && dry_food.present?
  end

  def amount_less_than_dry_food_left_amount
    return unless amount.present? && dry_food

    dry_food.reload(lock: true)
    if dry_food.left_amount < amount
      errors.add(:amount, :greater_than_left_amount, left_amount: dry_food.left_amount)
    end
  end

  after_commit :update_dry_food_on_create, on: :create
  after_commit :update_dry_food_on_destroy, on: :destroy

  private

  def dry_food?
    (kibble? || freeze_dried?) && dry_food.present?
  end

  def amount_less_than_dry_food_left_amount
    return unless amount.present? && dry_food

    dry_food.reload(lock: true)
    if dry_food.left_amount < amount
      errors.add(:amount, :greater_than_left_amount, left_amount: dry_food.left_amount)
    end
  end

  def update_dry_food_on_create
    dry_food&.update_used_amount!
  end

  def update_dry_food_on_destroy
    # On destroy, the association is still available in memory
    dry_food&.update_used_amount!
  end

  def self.to_csv
    require "csv"
    CSV.generate(headers: true, col_sep: ";") do |csv|
      csv << [ "date", "feed_time", "come_back_to_eat", "food_type", "brand", "description", "amount", "left_amount", "total_ate_amount", "hungry", "love", "result", "note", "weight" ]
      find_each do |tracker|
        csv << [
          tracker.date,
          tracker.feed_time&.strftime("%H:%M"),
          tracker.come_back_to_eat,
          tracker.food_type,
          tracker.brand,
          tracker.description,
          tracker.amount,
          tracker.left_amount,
          tracker.total_ate_amount,
          HUNGRY_MAP[tracker.hungry.to_sym],
          tracker.love,
          tracker.result,
          tracker.note,
          tracker.weight
        ]
      end
    end
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  # include TrackersCalculable
  before_action :set_pet
  before_action :set_tracker, only: %i[ show edit update destroy ]
  before_action :require_authentication
  before_action :set_current_date, :set_current_time

  def import
    file = params[:file]
    if file.nil? || file.content_type != "text/csv"
      return redirect_to pet_trackers_path, alert: t(".import.alert")
    end

    importer = CsvImportTrackersService.new(@pet)
    if importer.call(file)
      redirect_to pet_trackers_path, notice: t(".import.notice", petname: @pet.petname.capitalize)
    else
      redirect_to pet_trackers_path, alert: importer.errors.join(", ")
    end
  end

  # GET /trackers or /trackers.json
  def index
    # @trackers = Tracker.all
    # @all_trackers = @pet.trackers.order(date: :asc, feed_time: :asc)
    @all_trackers = @pet.trackers
    trackers_table = Tracker.arel_table

    # Add the following lines to filter the trackers based on the selected range
    case params[:range]
    when "7"
      @all_trackers = @all_trackers.where("date >= ?", 7.days.ago.to_date)
    when "30"
      @all_trackers = @all_trackers.where("date >= ?", 30.days.ago.to_date)
    end

    if params[:food_type].present?
      @all_trackers = @all_trackers.where(trackers_table[:food_type].matches("%#{params[:food_type]}%"))
    end

    if params[:brand].present?
      @all_trackers = @all_trackers.where(trackers_table[:brand].matches("%#{params[:brand]}%"))
    end

    if params[:description].present?
      @all_trackers = @all_trackers.where(trackers_table[:description].matches("%#{params[:description]}%"))
    end

    # @trackers = @all_trackers.paginate(page: params[:page], per_page: params[:per_page] || 10)
    page = params[:page].blank? ? 1 : params[:page]
    @trackers = @all_trackers.order(date: :asc, feed_time: :asc).paginate(page: page, per_page: params[:per_page].to_i > 0 ? params[:per_page] : 10)

    respond_to do |format|
      format.html
      format.csv do
        send_data Tracker.to_csv, filename: "#{@pet.petname.capitalize}-trackers-#{Date.today}.csv", type: "text/csv"
      end
    end

    hotel_keywords = [ "hotel", "旅館", "貓旅", "boarding", "resort" ]

    # Sanitize hotel keywords for LIKE query
    formatted_keywords = hotel_keywords.map { |k| "%#{k}%" }

    # Use Arel to safely construct the query for hotel stays
    hotel_conditions = formatted_keywords.map do |keyword|
      trackers_table[:note].matches(keyword)
    end.reduce(:or)

    # Use Arel to safely construct the query for normal stays (not in a hotel)
    normal_conditions = trackers_table[:note].eq(nil).or(hotel_conditions.not)

    dry_raw = @all_trackers.where(food_type: [ "Kibble", "Freeze-Dried" ]).where(normal_conditions).where.not(total_ate_amount: nil).group(:date).sum(:total_ate_amount)
    dry_hotel_raw = @all_trackers.where(food_type: [ "Kibble", "Freeze-Dried" ]).where(hotel_conditions).where.not(total_ate_amount: nil).group(:date).sum(:total_ate_amount)
    wet_raw = @all_trackers.where(food_type: "Wet").where(normal_conditions).where.not(total_ate_amount: nil).group(:date).sum(:total_ate_amount)
    wet_hotel_raw = @all_trackers.where(food_type: "Wet").where(hotel_conditions).where.not(total_ate_amount: nil).group(:date).sum(:total_ate_amount)

    all_dates = (dry_raw.keys + dry_hotel_raw.keys + wet_raw.keys + wet_hotel_raw.keys).uniq.sort

    format_chart_data = ->(hash, all_dates) {
      data = all_dates.map { |date| [ date.strftime("%y/%m/%d"), hash[date].to_f ] }
      data.to_h
    }

    @dry_properties = format_chart_data.call(dry_raw, all_dates)
    @dry_hotel_properties = format_chart_data.call(dry_hotel_raw, all_dates)
    @wet_properties = format_chart_data.call(wet_raw, all_dates)
    @wet_hotel_properties = format_chart_data.call(wet_hotel_raw, all_dates)
    # Using average for weight is safer than sum, in case multiple entries exist for one day.
    @weight = @all_trackers.where.not(weight: nil).group(:date).order(:date).average(:weight).transform_keys { |key| key.strftime("%y/%m/%d") }.transform_values(&:to_f)

    @data = [
      { name: t(".chart.wet_food"), data: @wet_properties },
      { name: "Wet (Hotel)", data: @wet_hotel_properties },
      { name: t(".chart.dry_food"), data: @dry_properties },
      { name: "Dry (Hotel)", data: @dry_hotel_properties },
      { name: t(".chart.weight"), data: @weight, type: "line" }
    ]
  end

  # GET /trackers/1 or /trackers/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @tracker }
    end
  end

  # GET /trackers/new
  def new
    # @tracker = Tracker.new
    @tracker = @pet.trackers.build
  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers or /trackers.json
  def create
    # @tracker = Tracker.new(tracker_params)
    @tracker = @pet.trackers.build(tracker_params)
    @tracker.dry_food_id = nil if params[:tracker][:dry_food_id].blank?

    respond_to do |format|
      if @tracker.save
        per_page = params[:per_page] || 10
        total_trackers = @pet.trackers.count
        page = (total_trackers.to_f / per_page.to_i).ceil
        format.html { redirect_to pet_trackers_path(@pet, page: page), notice: t(".create.notice") }
        format.json { render :show, status: :created, location: pet_trackers_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1 or /trackers/1.json
  def update
    # @tracker.update!(params.expect(tracker: [ :amount, :left_amount, :hungry, :come_back_to_eat, :love ]))
    @tracker.assign_attributes(tracker_params)
    @tracker.dry_food_id = nil if params[:tracker][:dry_food_id].blank?
    @tracker.total_ate_amount = @tracker.amount.to_f - @tracker.left_amount.to_f
    @tracker.frequency = calculate_frequency(@tracker.come_back_to_eat)
    if @tracker.hungry.present? && @tracker.love.present?
      result_parts = [ Tracker.hungries[@tracker.hungry.to_sym][0], @tracker.love[0] ]
      @tracker.result = result_parts.join(" - ")
      @tracker.favorite_score = calculate_favorite(result_parts)
    else
      @tracker.result = nil
      @tracker.favorite_score = 0
    end

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to pet_trackers_path(@pet, page: params[:tracker][:page]), notice: t(".update.notice"), status: :see_other }
        format.json { render :show, status: :ok, location: [ @pet, :trackers ] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1 or /trackers/1.json
  def destroy
    @tracker.destroy!

    respond_to do |format|
      format.html { redirect_to pet_trackers_path(@pet, page: params[:page]), notice: t(".destroy.notice"), status: :see_other }
      format.json { head :no_content }
    end
  end

  def favorite_food
    trackers = @pet.trackers.where.not(hungry: [ nil, "" ], love: [ nil, "" ]).order(date: :desc)

    if params[:food_type].present?
      trackers_table = Tracker.arel_table
      trackers = trackers.where(trackers_table[:food_type].matches("%#{params[:food_type]}%"))
    end

    @favorite_foods = trackers.group_by do |tracker|
      clean_description = tracker.description.to_s.gsub("（", "(").gsub("）", ")").gsub(/\s*[xX]\d+\z/, "").squish.downcase

      [ tracker.food_type.to_s.squish.downcase, tracker.brand.to_s.squish.downcase, clean_description ]
    end.map do |(food_type, brand, description), group_trackers|
      unique_daily_results = group_trackers.sort_by { |t| t.favorite_score }.reverse
                                          .uniq { |t| t.date }
      {
        food_type: food_type,
        brand: brand,
        description: description,
        count: group_trackers.size,
        results: unique_daily_results.first(5).sort_by { |t| t.date }.reverse.map do |t|
          {
            id: t.id,
            date: t.date.strftime("%y/%m/%d"),
            result: t.result,
            favorite_score: t.favorite_score
          }
        end
      }
    end

    require "will_paginate/array"
    @favorite_foods = @favorite_foods.sort_by { |f| f[:results].first[:favorite_score] }.reverse.paginate(page: params[:page], per_page: params[:per_page] || 10)


    # trackers = trackers.order(favorite_score: :desc)

    # unique_foods = trackers.each_with_object({}) do |tracker, hash|
    #   normalized_description = tracker.description.to_s.gsub(/\s*[xX]\d+\z/, "").strip
    #   key = [ tracker.brand, normalized_description ]
    #   hash[key] ||= tracker
    # end.values

    # require "will_paginate/array"
    # @favorite_foods = unique_foods.paginate(page: params[:page], per_page: params[:per_page] || 10)

    respond_to do |format|
      format.html
      format.json { render json: @favorite_foods }
    end
  end

  def bulk_delete
    @pet.trackers.where(id: params[:tracker_ids]).destroy_all
    respond_to do |format|
      format.html { redirect_to pet_trackers_path(@pet), notice: t(".bulk_delete.notice") }
      format.json { head :no_content }
    end
  end

  private
    def set_pet
      @pet = Pet.find(params[:pet_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      # @tracker = Tracker.find(params.expect(:id))
      @tracker = @pet.trackers.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = t(".set_tracker.alert")
        redirect_to pet_tracker_path
    end

    def set_current_time
      Time.zone = Current.user.timezone
      Time.current.strftime("%H:%M")
    end

    def set_current_date
      Time.zone = Current.user.timezone
      Date.current.strftime("%Y-%m-%d")
    end

    # Only allow a list of trusted parameters through.

app/helpers/trackers_helper.rb
module TrackersHelper
  def set_current_time
    Time.zone = Current.user.timezone
    Time.current.strftime("%H:%M")
  end

  def set_current_date
    Time.zone = Current.user.timezone
    Date.current.strftime("%Y-%m-%d")
  end

  def tracker_row_class(tracker)
    classes = [ "border-b" ]
    if tracker.come_back_to_eat.blank?
      classes << "bg-yellow-100"
    elsif tracker.total_ate_amount.blank?
      classes << "bg-red-100"
    elsif tracker.result.blank? || tracker.hungry.blank?
      classes << "bg-blue-200"
    end
    classes.join(" ")
  end
end

app/views/trackers/index.html.erb
<% content_for :title, t('trackers.index.title', petname: @pet.petname.capitalize) %>

  <details class="container mx-auto border-2 border-garyishBlue rounded-md shadow-md w-full lg:w-1/2">
    <summary class="text-center font-bold text-lg cursor-pointer p-2 md:text-base"><%= t('trackers.index.import_csv') %></summary>
    <div class="flex flex-col justify-center items-center mb-4">
      <%= form_with url: import_pet_trackers_path(@pet), method: :post do |form| %>
        <%= form.file_field :file, accept: ".csv" %>
        <%= form.button t('trackers.index.import_button'), class: "p-2 mt-4 rounded-md shadow-lg font-semibold border-2 border-blue-300 text-gray-700 bg-sky-200 hover:bg-gray-200 hover:border-gray-400 hover:text-sky-700 hover:scale-110" %>
        <div class="flex text-sm italic font-semibold text-gray-500">
          <span class="dark:text-grayishBlue"><%= t('trackers.index.import_hint') %></span>
        </div>
      <% end %>
    </div>
  </details>
  
  <div class="flex flex-col justify-center items-center mb-3">
    <h1 class="font-bold text-center text-2xl mt-5 md:text-4xl"><%= t('trackers.index.title', petname: @pet.petname.capitalize) %></h1>
  </div>

  <div class="flex flex-row justify-center space-x-3">
    <%= image_tag('add_tracker_removebg.png', width:'40px', height: '40px') %>
    <%= link_to t('trackers.index.new_tracker_link', petname: @pet.petname.capitalize), new_pet_tracker_path(@pet), class: "text-purple-500 text-lg underline decoration-2 decoration-purple-500 font-bold transition duration-300 ease-in-out hover:scale-110 capitalize md:text-xl" %>
  </div>

  <fieldset class="flex flex-row gap-3 justify-center mb-3">
    <%= image_tag('download.png', width: '25px', height: '25px') %>
    <%= link_to t('trackers.index.export_csv'), pet_trackers_path(@pet, format: :csv), class: "text-base font-bold text-sky-500 transition duration-300 ease-in-out hover:scale-110 capitalize md:text-lg dark:text-white" %>
  </fieldset>

  <div class="flex flex-col digg_pagination justify-center italic mt-4">
    <div class="flex justify-center page_info">
      <%= page_entries_info @trackers %>
    </div>

    <div class="flex digg_pagination justify-center mt-4">
      <%= will_paginate @trackers, :container => true %>
    </div>
    <div class="flex justify-end items-start mx-8">
      <%= form_with url: pet_trackers_path(@pet), method: :get, class: "flex items-center" do |form| %>
        <span class="mr-2"><%= t('trackers.index.items_per_page') %></span>
        <%= form.select :per_page, options_for_select([5, 10, 20, 50], params[:per_page] || 10), {}, { onchange: 'this.form.submit()', class: "p-1 rounded-md shadow-lg font-semibold border-2 border-blue-300 text-gray-700 bg-sky-200 hover:bg-gray-200 hover:border-gray-400 hover:text-sky-700" } %>
      <% end %>
    </div>
  </div>


  <div class="flex flex-col mt-5 mb-4 justify-center items-center mx-auto w-full">
    <div class="flex justify-end items-end pr-8 pt-4 mb-4 w-full">
      <%= form_with url: pet_trackers_path(@pet), method: :get, class: "flex items-center" do |form| %>
        <span class="mr-2"><%= t('trackers.index.chart_range') %></span>
        <%= form.select :range, options_for_select([[t('trackers.index.all_time'), "all"], [t('trackers.index.last_7_days'), "7"], [t('trackers.index.last_30_days'), "30"]], params[:range] || "all"), {}, { onchange: 'this.form.submit()', class: "p-1 rounded-md shadow-lg font-semibold border-2 border-blue-300 text-gray-700 bg-sky-200 hover:bg-gray-200 hover:border-gray-400 hover:text-sky-700" } %>
      <% end %>
    </div>

    <% if @dry_properties.present? || @wet_properties.present? %>
      <%= column_chart @data, adapter: "google", height: "300px", library: {
        title: t('trackers.index.chart_title'),
        isStacked: true,
        interpolateNulls: true,
        series: {
          0 => {type: 'bar', targetAxisIndex: 0},
          1 => {type: 'bar', targetAxisIndex: 0},
          2 => {type: 'bar', targetAxisIndex: 0},
          3 => {type: 'bar', targetAxisIndex: 0},
          4 => {type: 'line', targetAxisIndex: 1, pointSize: 5}
        },
        colors: ['#C1D7EC', '#2563EB', '#FFDAB9','#F97316', '#6B4AB9'],
        chartArea: {left: 100, right: 100},
        hAxis: {
          title: t('trackers.index.chart_h_axis_title'),
          titleTextStyle: {italic: true}
        },
        vAxes: {
          0 => {title: t('trackers.index.chart_v_axis_amount')},
          1 => {title: t('trackers.index.chart_v_axis_weight'), viewWindow: {min: 0, max: 15}, gridlines: {color: 'transparent'}}
        },
        legend: {position: 'top'},
        titleTextStyle: {bold: true, fontSize: 20},
      } %>
    <% else %>
      <div class="text-center p-8 my-4 bg-gray-100 rounded-lg shadow-lg">
        <p class="font-semibold text-gray-700"><%= t('trackers.index.no_data_for_chart') %></p>
      </div>
    <% end %>
  </div>

  <div id="trackers" class="container mx-auto flex flex-col divide-y divide-gray-200 space-y-5">
    <%= form_with url: pet_trackers_path(@pet), method: :get, data: { controller: "filter-form" } do |form| %>
      <% if @trackers.any? %>
        <div class="flex flex-row gap-4">
          <div class="flex items-center mt-4">
            <%= form.label :food_type, "Food Type", class: "text-sm font-medium text-gray-700 p-4 dark:text-gray-100 capitalize md:text-base whitespace-nowrap" %>
            <%= form.text_field :food_type, value: params[:food_type], class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full dark:text-black", data: { action: "input->filter-form#submit" } %>
          </div>
          <div class="flex items-center mt-4">
            <%= form.label :brand, "Brand", class: "text-sm font-medium text-gray-700 p-4 dark:text-gray-100 capitalize md:text-base" %>
            <%= form.text_field :brand, value: params[:brand], class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full dark:text-black", data: { action: "input->filter-form#submit" } %>
          </div>
          <div class="flex items-center mt-4">
            <%= form.label :description, "Description", class: "text-sm font-medium text-gray-700 p-4 dark:text-gray-100 capitalize md:text-base" %>
            <%= form.text_field :description, value: params[:description], class: "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full dark:text-black", data: { action: "input->filter-form#submit" } %>
          </div>
          <div class="flex items-center mt-4">
            <%= link_to "Clear", pet_trackers_path(@pet), class: "py-2 px-3 mt-2 rounded-md shadow-lg font-semibold border-2 border-gray-300 text-gray-700 bg-gray-200 hover:bg-gray-300 hover:border-gray-400 hover:text-gray-600 hover:bg-gray-100 hover:scale-110" %>
          </div>
        </div>
      <% end %>
    <% end %>

    <%= form_with url: bulk_delete_pet_trackers_path(@pet), method: :delete, data: { confirm: t('trackers.index.confirm_delete') } do |form| %>
      <% if @trackers.any?%>
        <div class="flex justify-start mt-4">
          <%= form.submit t('trackers.index.delete_selected'), class: "p-2 rounded-md shadow-lg font-semibold border-2 border-red-300 text-gray-700 bg-red-200 hover:bg-gray-100 hover:border-gray-300 hover:text-red-700 hover:scale-110" %>
        </div>
        <%= render 'tracker' %>
      <% else %>
        <p class="text-lg text-center my-10"><%= t('trackers.tracker.no_trackers_found', petname: @pet.petname) %></p>
        <div class="flex justify-center mb-4 items-center">
          <%= link_to "Back to #{@pet.petname.capitalize}'s Trackers", pet_trackers_path(@pet, page: params[:page]), class: "text-center rounded-md px-3.5 py-2.5 text-white bg-grayishBlue shadow-md hover:bg-white hover:text-grayishBlue hover:border-2 hover:border-grayishBlue hover:scale-110 inline-block font-medium cursor-pointer" %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="flex digg_pagination justify-center mb-4 mt-4">
    <div class="page_info italic">
      <%= page_entries_info @trackers %>
    </div>
  </div>
  <div class="flex digg_pagination justify-center mt-4 mb-4 italic">
    <%= will_paginate @trackers, :container => true %>
  </div>
</div>

app/views/trackers/new.html.erb
<% content_for :title, t('trackers.new.title') %>

<div class="container mx-auto md:w-2/3 w-full" data-controller="tracker-form">

  <div class="flex flex-row justify-center gap-4 mb-4 dark:bg-gray-800 p-4 sm:p-6">
    <%= image_tag('tracker_removebg.png', width: '48px', height: '40px') %>
    <h1 class="text-center font-bold text-2xl mt-4 capitalize lg:text-4xl"><%= t('trackers.new.header') %></h1>
  </div>

  <%= render "form", tracker: @tracker %>

  <div class="flex flex-col justify-center items-center gap-4 mb-4 pt-4 md:flex-row">
    <div class="flex justify-center">
      <%= button_tag(t('trackers.new.add_button', petname: @pet.petname.capitalize), type: "submit", form: "tracker-form", class: "btn text-center rounded-md px-3.5 py-2.5 text-white bg-softBlue hover:bg-white hover:text-softBlue hover:border-2 hover:border-softBlue inline-block font-medium cursor-pointer capitalize", data: { tracker_form_target: "submitButton" }) %>
    </div>
    <div class="flex justify-center">
      <%= link_to t('trackers.new.back_button', petname: @pet.petname), pet_trackers_path, class: "text-center rounded-md px-3.5 py-2.5 text-white bg-gray-500 hover:bg-white hover:text-gray-500 hover:border-2 hover:border-gray-500 inline-block font-medium cursor-pointer capitalize" %>
    </div>
  </div>

</div>

app/views/trackers/show.html.erb
<% content_for :title, t('trackers.show.title') %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl"><%= t('trackers.show.header') %></h1>

  <%= render 'tracker' %>

  <%= link_to t('trackers.show.edit_button'), edit_pet_tracker_path(@pet, @tracker), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to t('trackers.show.back_button'), pet_trackers_path(@pet), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to t('trackers.show.destroy_button'), pet_tracker_path(@pet, @tracker), method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: t('trackers.show.confirm') } %>
</div>