config/routes.rb
Rails.application.routes.draw do
  # resources :trackers
  root "pages#hero_section"
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :dry_foods, only: [ :new, :create, :index, :destroy, :show ]
    resources :pets do
      resources :trackers do
        collection do
          post :import
          get "favorite_food"
          delete :bulk_delete
        end
      end
    end
    resource :session, except: [ :new ]
    resource :registrations, only: [ :new, :create ]
    resource :timezone, only: [ :create ]
    resource :users, except: [ :new ]
    # get '/signup', to: "registrations#new", as: :new_registrations
    # post 'registration/create', to: "registrations#create", as: :registrations
    get "/login", to: "sessions#new", as: :new_session
    resources :passwords, only: [ :new, :create, :edit, :update ], param: :token
    get "/home", to: "pages#hero_section"
    get "/about", to: "pages#about"
    get "/doc", to: "pages#doc"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "auth/:provider/callback", to: "omni_auth/sessions#create"
  post "auth/:provider/callback", to: "omni_auth/sessions#create"
  get "auth/failure", to: "omni_auth/sessions#failure"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_footer.html.erb
<footer class="py-16 bg-veryDarkBlue">
  <div class="container flex flex-col items-center justify-between mx-auto space-y-16 px-6 md:flex-row md:space-y-0">
    <div class="flex flex-col items-center justify-between space-y-8 text-lg font-light md:flex-row md:space-y-0 md:space-x-14 text-grayishBlue">
      <%= image_tag('footer_aji_logo.png', width: "80px") %>
      <a href="/home#features" class="uppercase hover:text-softRed"><%= t('layouts.footer.features') %></a>
      <%= link_to t('layouts.footer.about'), about_path, class: 'uppercase hover:text-softRed'%>
      <%= link_to t('layouts.footer.docs'), doc_path, class: 'uppercase hover:text-softRed'%>
      <% if authenticated? %>
        <%= button_to t('layouts.footer.sign_out'), session_path, class: "px-8 py-2 uppercase text-white bg-softRed border-2 border-softRed rounded-lg shadow-md hover:text-softRed hover:bg-white", method: :delete %>
      <% else %>
        <%= link_to t('layouts.footer.get_started'), new_registrations_path, class: 'uppercase hover:text-softRed'%>
      <% end %>
    </div>

    <div class="flex flex-col items-center space-x-10 space-y-8">
      <div class="flex flex-row justify-center space-x-10">
        <a href="https://www.linkedin.com/in/yuruhuang/" target="_blank" class='h-6 ficon'>
          <svg stroke-width="0" viewBox="0 0 25 25" height="35px" width="35px" xmlns="http://www.w3.org/2000/svg">
            <g>
              <path fill="#f0f4e9" d="M18.44,3.06H5.56a2.507,2.507,0,0,0-2.5,2.5V18.44a2.507
                  ,2.507,0,0,0,2.5,2.5H18.44a2.5,2.5,0,0,0,2.5-2.5V5.56A2.5,2.5,0,
                  0,0,18.44,3.06Zm1.5,15.38a1.511,1.511,0,0,1-1.5,1.5H5.56a1.511,
                  1.511,0,0,1-1.5-1.5V5.56a1.511,1.511,0,0,1,1.5-1.5H18.44a1.511,1.511,
                  0,0,1,1.5,1.5Z"></path>
            </g>
            <g>
              <path fill="#f0f4e9" d="M6.376,10.748a1,1,0,1,1,2,0v6.5h0a1,1,0,0,1-2,0Z"></path>
              <circle fill="#f0f4e9" cx="7.376" cy="6.744" r="1"></circle>
              <path fill="#f0f4e9" d="M17.62,13.37v3.88a1,1,0,1,1-2,0V13.37a1.615,1.615,0,1,0-3.23,0v3.88
              a1,1,0,0,1-2,0v-6.5a1.016,1.016,0,0,1,1-1,.94.94,0,0,1,.84.47,3.609,3.609,0,
              0,1,5.39,3.15Z"></path>
            </g>
          </svg>
        </a>
        <a href="https://github.com/yuhruh" target="_blank" class='h-6 ficon'>
          <svg fill="#ffffff" stroke-width="0" viewBox="0 0 496 512" height="25px" width="25px" xmlns="http://www.w3.org/2000/svg">
            <path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2
            1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 
            5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 
            2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 
            2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 
            23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 
            69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 
            33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 
            1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 
            4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 
            1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 
            0-6.2-1.4-2.3-4-3.3-5.6-2z">
            </path>
          </svg>
        </a>
      </div>
      <div class="flex flex-col justify-center text-white font-bold"><%= t('layouts.footer.copyright') %></div>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container flex justify-center mx-auto">
  <% flash.each do |name, msg| %>
    <div id="alert-message" class="flex justify-between text-start items-center p-4 mb-4 text-base rounded-lg <%= name == 'notice' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700' %> transition-opacity duration-300 ease-in opacity-100 w-full md:w-2/3" role="alert">
      <div>
        <%= msg %>
      </div>
      <button type="button" class="text-2xl font-bold" onclick="closeAlert()" aria-label="Close">&times;</button>
    </div>
  <% end %>
</div>

<script>
  function closeAlert() {
    const alertMessage = document.getElementById('alert-message');
    if (alertMessage) {
      alertMessage.style.opacity = '0';
      setTimeout(() => {
        alertMessage.remove();
      }, 300);
    }
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="scroll-smooth" lang="<%= I18n.locale %>">
  <head>
    <title><%= content_for(:title) || "Aji Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= favicon_link_tag 'aji_favicon_32.png' %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body class="dark:bg-darkBlue dark:text-white overflow-x-hidden">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
      <%= yield %>
    <div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>